### ISSUE TITLE
Retain Issue - Subject retaining disposed observers

### ISSUE THREAD

**Issue by AnthonyMillerSF** [DeclarativeHub/ReactiveKit#238] opened 2019-11-20 00:00 UTC
I'm hitting a bug in my production code that is causing a retain cycle. Unfortunately I am unable to provide a code sample, as the use case is proprietary currently. But I can explain what's causing it.

I've made a [comment here](https://github.com/DeclarativeHub/ReactiveKit/commit/afb661b04b8270b256f5a23c612d9db6514f2ca7#r36039816) with a question about the code that has caused this retain cycle. I thought it was best to create an issue here as well to track the issue and the conversation around it. 

Feel free to close this if you don't want to track this as an issue.

**Comment by srdanrasic** [comment] 2019-12-07 10:01
@AnthonyMDev has this maybe been fixed by your PR?

**Comment by AnthonyMDev** [comment] 2019-12-09 20:17
@srdanrasic No, this is a separate issue. I'd be happy to make a PR for this, but I wanted to get your opinion on the best way to solve it first. @trupin suggested making the `_deletedObservers` a set of weak references. Does that seem like the right solution to you? If so, I'll make a PR for it.

**Comment by trupin** [comment] 2019-12-19 22:52
@AnthonyMillerSF, I will be running some tests today to check if making `_deletedObservers` a set of weak references works for us or not. Will let you know.

**Comment by trupin** [comment] 2019-12-20 21:27
So @AnthonyMillerSF, after auditing the code, I don't think making the deleted observers weak references will work.

After auditing the code, I think that no retaining the deleted observers until receiving the next event can still cause dead locks on our side.

Could you eventually write a sample of code which reproduces the retain cycle that you see? Maybe we could try tackle the problem this way as dealing with retain cycles is usually less tricky than dead locks.

**Comment by AnthonyMDev** [comment] 2019-12-21 00:12
Thanks so much for looking into this! I can try to write a test the reproduces the retain cycle for you next week on Monday! Appreciate your help!

**Comment by stevenkramer** [comment] 2020-01-03 12:46
@srdanrasic @AnthonyMDev I've just started trying out ReactiveKit (liking it so far BTW) and immediately noticed this issue. I don't think making `_deletedObservers` weak ref the observers will help, because the use case here is that the Subject already owns the last strong ref, right? I.e. you would  I 'solved' this by making the pruning of observers a public API. So it's `obs.dispose(); subjec.pruneObservers();` for now. Not great but it solves my problem.

**Comment by srdanrasic** [comment] 2020-01-03 14:23
Thanks everyone for driving this forward! I've released v3.15.5 where subjects no longer retain disposed observers. Please confirm is this is still an issue.

**Comment by AnthonyMDev** [comment] 2020-01-03 21:01
Thanks so much @srdanrasic! I'll do some testing today on this, but after looking at the fixing commit (https://github.com/DeclarativeHub/ReactiveKit/commit/0b027733862717ee048c4702d387ae25255eb182) I'm concerned this might reintroduce the deadlock that @trupin initially tried to fix. 
@trupin do you mind taking a look at this and verifying whether this re-creates a deadlock?

**Comment by srdanrasic** [comment] 2020-01-04 13:40
I hope it won't, but if it does, there has to be another solution to it because retaining observers leads to silent problems.

**Comment by trupin** [comment] 2020-01-13 18:06
@AnthonyMDev, @srdanrasic, thanks for looking into this. I will do some testing today to see if the dead lock was reintroduced.

**Comment by srdanrasic** [comment] 2020-01-18 09:45
I've been doing a lot of testing this week and I haven't seen any issue. I'll close this for now, but we can reopen it if the issue appears again.

**Closed by srdanrasic** 2020-01-18 09:45 UTC

**Comment by trupin** [comment] 2020-01-19 15:57
Same, here, our tests didn't show any issue.

**Comment by AnthonyMillerSF** [comment] 2020-01-20 22:32
That's awesome. So glad this is resolved. You guys rock.

**Comment by srdanrasic** [comment] 2020-01-21 07:57
Thanks @trupin and @AnthonyMDev for reporting and helping out on this one!
